import { Link } from "react-router-dom";
import { ArrowUpRight, Compass, Sparkles, Building2, Calendar, Award, Shield, Brain, Rocket, MapPin, FileText, CheckCircle2, AlertTriangle, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import ThemeToggle from "@/components/ThemeToggle";
import Disclaimer from "@/components/Disclaimer";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { useProfile } from "@/lib/profile";
import { useNavigate } from "react-router-dom";

const features = [
  { icon: Brain, title: "AI Founder Copilot", text: "Ask anything — GST, registrations, schemes, funding. Personalised to your stage, state, industry." },
  { icon: Calendar, title: "Compliance Dashboard", text: "GST, MCA, TDS, PF, ESI — every due date in one place. Color-coded calendar with penalty info." },
  { icon: Award, title: "Government Benefits Engine", text: "Startup India, CGTMSE, Mudra, PMEGP, ELEVATE, StartupTN, MSInS — matched to your profile." },
  { icon: MapPin, title: "State Intelligence", text: "All 28 states + 8 UTs. Grants, subsidies, professional tax, registrations — by your state." },
  { icon: FileText, title: "License Recommender", text: "FSSAI, Labour, Factory, Pollution NOC, Drug, Clinical — for your industry & state." },
  { icon: Shield, title: "Trademark & IP Advisor", text: "Class recommendations, filing cost (₹4,500 for startups), IP checklist, patent opportunity." },
  { icon: Rocket, title: "Personalised Roadmap", text: "30 / 90 / 180 / 365 day roadmap auto-generated by AI for your specific journey." },
  { icon: CheckCircle2, title: "Startup Health Score", text: "/100 score across registrations, compliance, funding readiness, documentation, IP." },
];

const faqs = [
  { q: "Is Bharat Startup Desk a registration agent or consultant?", a: "No. We're an educational guidance platform. We help you understand what you need and how to do it yourself or via authorised portals. We never charge for government services." },
  { q: "Does the AI give legal or tax advice?", a: "No. The AI gives general educational guidance based on publicly available information. For binding legal or tax decisions, please consult a qualified Chartered Accountant or Company Secretary." },
  { q: "Which states do you cover?", a: "All 28 states and 8 Union Territories of India. We deeply curate scheme and benefit data for high-activity ecosystems — Karnataka, Maharashtra, Tamil Nadu, Telangana, Gujarat, Delhi NCR — and growing." },
  { q: "Is my data secure?", a: "We store only what you enter to personalise your dashboard. No real government APIs are queried in this demo. You can delete your profile any time." },
  { q: "Can I use this without registering?", a: "Yes. The 'Explore My Startup Idea' flow needs no login. Try Demo mode to see a full dashboard instantly." },
];

const stats = [
  { num: "10", suffix: "+", label: "Schemes curated" },
  { num: "36", suffix: "", label: "States & UTs" },
  { num: "20", suffix: "+", label: "Industries" },
  { num: "100", suffix: "%", label: "Self-service" },
];

export default function Landing() {
  const [demos, setDemos] = useState([]);
  const { setProfile } = useProfile();
  const nav = useNavigate();

  useEffect(() => {
    api.get("/demo/startups").then(r => setDemos(r.data.startups)).catch(() => {});
  }, [setDemos]);

  const loadDemo = (d) => {
    setProfile({ ...d, is_demo: true });
    nav("/dashboard");
  };

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* NAV */}
      <header className="sticky top-0 z-50 glass-nav bg-background/70 border-b border-border">
        <div className="max-w-7xl mx-auto px-6 lg:px-10 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2" data-testid="logo-link">
            <div className="h-8 w-8 rounded-md bg-primary text-primary-foreground grid place-items-center font-display font-bold">B</div>
            <span className="font-display text-lg font-bold">Bharat Startup Desk</span>
          </Link>
          <nav className="hidden md:flex items-center gap-7 text-sm">
            <a href="#features" className="hover:text-primary transition-colors">Features</a>
            <a href="#how" className="hover:text-primary transition-colors">How it works</a>
            <a href="#pricing" className="hover:text-primary transition-colors">Pricing</a>
            <a href="#faq" className="hover:text-primary transition-colors">FAQ</a>
          </nav>
          <div className="flex items-center gap-2">
            <ThemeToggle />
            <Button asChild data-testid="nav-explore-btn" size="sm" className="hidden sm:inline-flex">
              <Link to="/explore">Explore <ArrowUpRight className="ml-1 h-4 w-4" /></Link>
            </Button>
          </div>
        </div>
      </header>

      {/* HERO */}
      <section className="relative overflow-hidden border-b border-border">
        <div className="absolute inset-0 dot-pattern opacity-40 pointer-events-none" />
        <div className="max-w-7xl mx-auto px-6 lg:px-10 pt-20 pb-24 grid lg:grid-cols-12 gap-10 items-start relative">
          <div className="lg:col-span-7 fade-up">
            <div className="inline-flex items-center gap-2 border border-border rounded-full px-3 py-1 mb-6 bg-card">
              <span className="h-1.5 w-1.5 rounded-full bg-accent animate-pulse" />
              <span className="label-eyebrow">Built for Indian founders · MSMEs · Startups</span>
            </div>
            <h1 className="font-display text-5xl md:text-6xl lg:text-7xl font-bold leading-[0.95] tracking-tighter">
              Your AI<br/>
              <span className="text-primary">co-founder</span> for<br/>
              building in <span className="italic font-medium">Bharat.</span>
            </h1>
            <p className="mt-6 text-lg text-muted-foreground max-w-xl leading-relaxed">
              Navigate registrations, GST, MCA filings, schemes & funding — without consultants. Personalised by stage, industry and state. Start with one question.
            </p>
            <div className="mt-8 flex flex-wrap gap-3" data-testid="hero-cta-row">
              <Button asChild size="lg" data-testid="explore-idea-btn" className="rounded-md">
                <Link to="/explore"><Compass className="mr-2 h-4 w-4" /> Explore My Idea</Link>
              </Button>
              <Button asChild size="lg" variant="outline" data-testid="start-journey-btn" className="rounded-md">
                <Link to="/onboarding"><Sparkles className="mr-2 h-4 w-4" /> Start My Journey</Link>
              </Button>
              <Button asChild size="lg" variant="outline" data-testid="already-registered-btn" className="rounded-md">
                <Link to="/register-business"><Building2 className="mr-2 h-4 w-4" /> Already Registered</Link>
              </Button>
            </div>
            <div className="mt-6">
              <Button
                onClick={() => demos[0] && loadDemo(demos[0])}
                data-testid="explore-demo-btn"
                className="rounded-md bg-foreground text-background hover:bg-foreground/90 h-12 px-6 font-semibold"
              >
                <Rocket className="mr-2 h-4 w-4" /> Explore Demo (1-click)
              </Button>
              <span className="ml-3 text-xs text-muted-foreground font-mono">No signup. See a fully-loaded dashboard.</span>
            </div>

            <div className="mt-10 grid grid-cols-4 gap-6 max-w-xl">
              {stats.map(s => (
                <div key={s.label} className="">
                  <div className="font-display text-3xl font-bold">{s.num}<span className="text-primary">{s.suffix}</span></div>
                  <div className="text-xs text-muted-foreground mt-1">{s.label}</div>
                </div>
              ))}
            </div>
          </div>

          <div className="lg:col-span-5 fade-up">
            <div className="rounded-lg border border-border bg-card overflow-hidden shadow-sm">
              <div className="border-b border-border px-4 py-2 flex items-center gap-2 bg-secondary/50">
                <div className="h-2.5 w-2.5 rounded-full bg-destructive/60" />
                <div className="h-2.5 w-2.5 rounded-full bg-warning/70" />
                <div className="h-2.5 w-2.5 rounded-full bg-success/70" />
                <span className="ml-3 text-[11px] font-mono text-muted-foreground">copilot.bharatstartupdesk.in</span>
              </div>
              <div className="p-5 space-y-4">
                <div className="text-xs label-eyebrow text-muted-foreground">Founder asked</div>
                <div className="text-sm leading-relaxed">Do I need GST if I am running a D2C skincare brand from Mumbai with ₹35L turnover?</div>
                <div className="text-xs label-eyebrow text-primary mt-4">Copilot answered</div>
                <div className="text-sm leading-relaxed text-muted-foreground">
                  Yes. For goods (skincare), GST registration becomes mandatory once turnover crosses <span className="text-foreground font-medium">₹40 Lakh</span>, but for inter-state supply or e-commerce (Amazon, Nykaa) it's mandatory from day one — irrespective of turnover. Since you're D2C in Maharashtra, you almost certainly need GSTIN now…
                </div>
                <div className="grid grid-cols-3 gap-2 pt-2">
                  <div className="border border-border rounded-md p-2">
                    <div className="text-[10px] font-mono text-muted-foreground">GST</div>
                    <div className="text-xs font-semibold mt-0.5">Mandatory</div>
                  </div>
                  <div className="border border-border rounded-md p-2">
                    <div className="text-[10px] font-mono text-muted-foreground">Trademark</div>
                    <div className="text-xs font-semibold mt-0.5">Class 3</div>
                  </div>
                  <div className="border border-border rounded-md p-2">
                    <div className="text-[10px] font-mono text-muted-foreground">Scheme</div>
                    <div className="text-xs font-semibold mt-0.5">MSInS ₹15L</div>
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-3"><Disclaimer compact /></div>
          </div>
        </div>
      </section>

      {/* PROBLEM */}
      <section className="border-b border-border">
        <div className="max-w-7xl mx-auto px-6 lg:px-10 py-20 grid lg:grid-cols-12 gap-10">
          <div className="lg:col-span-4">
            <div className="label-eyebrow text-primary">The problem</div>
            <h2 className="font-display text-4xl md:text-5xl font-bold tracking-tighter mt-3">India builds. India also drowns in paperwork.</h2>
          </div>
          <div className="lg:col-span-8 grid sm:grid-cols-2 gap-5">
            {[
              ["Fragmented compliance", "GST, MCA, TDS, PF — five portals, ten passwords, twelve deadlines."],
              ["Hidden schemes", "Most founders never discover the ₹50L grant they qualify for."],
              ["State-specific blind spots", "Karnataka ELEVATE, StartupTN, MSInS — each different, none centralised."],
              ["Consultant tax", "₹15K - ₹2L lost on basic registrations a founder could do themselves."],
            ].map(([t, d]) => (
              <div key={t} className="border border-border rounded-md p-5 bg-card hover-lift">
                <AlertTriangle className="h-5 w-5 text-warning" strokeWidth={1.5} />
                <div className="font-display font-semibold mt-3">{t}</div>
                <div className="text-sm text-muted-foreground mt-1.5 leading-relaxed">{d}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section id="features" className="border-b border-border">
        <div className="max-w-7xl mx-auto px-6 lg:px-10 py-24">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-12">
            <div>
              <div className="label-eyebrow text-primary">Everything you need</div>
              <h2 className="font-display text-4xl md:text-5xl font-bold tracking-tighter mt-3">One operating system. <br/>Every milestone.</h2>
            </div>
            <p className="text-muted-foreground max-w-md">From idea to ₹100 Cr ARR — registrations, compliance, schemes, IP, funding, roadmap. All personalised. All in one place.</p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-px bg-border border border-border rounded-lg overflow-hidden">
            {features.map(f => (
              <div key={f.title} className="bg-card p-6 hover-lift">
                <f.icon className="h-6 w-6 text-primary" strokeWidth={1.5} />
                <div className="font-display font-semibold text-lg mt-4">{f.title}</div>
                <div className="text-sm text-muted-foreground mt-2 leading-relaxed">{f.text}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section id="how" className="border-b border-border bg-secondary/30">
        <div className="max-w-7xl mx-auto px-6 lg:px-10 py-24">
          <div className="label-eyebrow text-primary">How it works</div>
          <h2 className="font-display text-4xl md:text-5xl font-bold tracking-tighter mt-3 mb-12">Three paths. One destination: clarity.</h2>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              { n: "01", title: "Explore My Idea", text: "Drop your idea. Get business structure, licenses, GST, schemes, 12-month roadmap — instantly. No signup.", to: "/explore", testid: "how-explore" },
              { n: "02", title: "Idea / MVP Stage", text: "Share startup name, stage, industry & state. Get compliance checklist, scheme matches, health score.", to: "/onboarding", testid: "how-onboarding" },
              { n: "03", title: "Already Registered", text: "Enter CIN / GSTIN / Udyam. We simulate public data, prepopulate your dashboard. You verify & go.", to: "/register-business", testid: "how-registered" },
            ].map(s => (
              <Link to={s.to} data-testid={s.testid} key={s.n} className="group border border-border rounded-lg bg-card p-6 hover-lift block">
                <div className="font-mono text-primary text-sm">{s.n}</div>
                <div className="font-display font-bold text-2xl mt-3">{s.title}</div>
                <div className="text-sm text-muted-foreground mt-2 leading-relaxed">{s.text}</div>
                <div className="mt-6 inline-flex items-center text-sm font-medium text-primary">
                  Start <ChevronRight className="h-4 w-4 ml-1 group-hover:translate-x-1 transition-transform" />
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* DEMO MODE */}
      <section className="border-b border-border">
        <div className="max-w-7xl mx-auto px-6 lg:px-10 py-24">
          <div className="flex items-end justify-between mb-10 flex-wrap gap-4">
            <div>
              <div className="label-eyebrow text-primary">Demo Mode</div>
              <h2 className="font-display text-4xl md:text-5xl font-bold tracking-tighter mt-3">See it in 60 seconds.</h2>
              <p className="text-muted-foreground mt-3 max-w-lg">Pick a preloaded Indian startup. We'll walk you straight into a fully-loaded dashboard with compliance, schemes, and AI plan ready.</p>
            </div>
          </div>
          <div className="grid md:grid-cols-3 gap-5">
            {demos.map((d, i) => (
              <button
                key={d.id}
                data-testid={`demo-startup-${i}`}
                onClick={() => loadDemo(d)}
                className="text-left border border-border rounded-lg bg-card p-6 hover-lift hover:border-primary"
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-mono uppercase tracking-wider text-muted-foreground">{d.stage}</span>
                  <span className="text-xs font-mono bg-secondary px-2 py-0.5 rounded">{d.state}</span>
                </div>
                <div className="font-display font-bold text-2xl mt-4">{d.name}</div>
                <div className="text-sm text-muted-foreground mt-1">{d.industry}</div>
                <div className="text-sm text-foreground/80 mt-4 line-clamp-3 leading-relaxed">{d.description}</div>
                <div className="mt-6 inline-flex items-center text-sm font-medium text-primary">
                  Load dashboard <ChevronRight className="h-4 w-4 ml-1" />
                </div>
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* TESTIMONIALS */}
      <section className="border-b border-border bg-secondary/30">
        <div className="max-w-7xl mx-auto px-6 lg:px-10 py-24">
          <div className="label-eyebrow text-primary">Loved by founders</div>
          <h2 className="font-display text-4xl md:text-5xl font-bold tracking-tighter mt-3 mb-12">Built with founder feedback.</h2>
          <div className="grid md:grid-cols-3 gap-5">
            {[
              { q: "I almost paid ₹85,000 to a consultant for things I could do myself in 3 days. This would've saved me that.", n: "Priya Iyer", r: "Founder, AyurGlow (D2C, Mumbai)" },
              { q: "The state-wise scheme matcher is incredible. I had no idea ELEVATE existed.", n: "Karthik R", r: "Co-founder, NeuralForge (AI SaaS, Bengaluru)" },
              { q: "Compliance calendar alone is worth it. Missed GSTR-3B once. Cost ₹12K in penalty. Never again.", n: "Manoj Patil", r: "MD, Karnataka Precision Forge" },
            ].map((t, i) => (
              <figure key={i} className="border border-border rounded-lg bg-card p-6">
                <blockquote className="text-foreground/90 leading-relaxed">“{t.q}”</blockquote>
                <figcaption className="mt-5 pt-5 border-t border-border">
                  <div className="font-semibold text-sm">{t.n}</div>
                  <div className="text-xs text-muted-foreground mt-0.5">{t.r}</div>
                </figcaption>
              </figure>
            ))}
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" className="border-b border-border">
        <div className="max-w-7xl mx-auto px-6 lg:px-10 py-24">
          <div className="label-eyebrow text-primary">Pricing</div>
          <h2 className="font-display text-4xl md:text-5xl font-bold tracking-tighter mt-3 mb-12">Free where it matters. Paid where it scales.</h2>
          <div className="grid md:grid-cols-3 gap-5">
            {[
              { plan: "Explore", price: "₹0", tag: "Forever free", desc: "Idea exploration, compliance reference, scheme directory.", cta: "Start free", to: "/explore", testid: "pricing-explore" },
              { plan: "Founder", price: "₹499", tag: "Per month", desc: "Full dashboard, AI copilot, personalised roadmap, document checklist.", cta: "Start journey", to: "/onboarding", testid: "pricing-founder", featured: true },
              { plan: "Growth", price: "₹1,999", tag: "Per month", desc: "Multi-entity, team seats, priority AI, scheme application support.", cta: "Talk to us", to: "/onboarding", testid: "pricing-growth" },
            ].map((p) => (
              <div key={p.plan} className={`border rounded-lg bg-card p-6 hover-lift ${p.featured ? "border-primary ring-1 ring-primary" : "border-border"}`}>
                {p.featured && <div className="label-eyebrow text-primary mb-3">Most popular</div>}
                <div className="font-display font-bold text-2xl">{p.plan}</div>
                <div className="mt-3 flex items-baseline gap-2">
                  <span className="font-display text-4xl font-bold">{p.price}</span>
                  <span className="text-sm text-muted-foreground">{p.tag}</span>
                </div>
                <p className="text-sm text-muted-foreground mt-3 leading-relaxed">{p.desc}</p>
                <Button asChild data-testid={p.testid} className="w-full mt-6" variant={p.featured ? "default" : "outline"}>
                  <Link to={p.to}>{p.cta}</Link>
                </Button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="border-b border-border">
        <div className="max-w-4xl mx-auto px-6 lg:px-10 py-24">
          <div className="label-eyebrow text-primary">FAQ</div>
          <h2 className="font-display text-4xl md:text-5xl font-bold tracking-tighter mt-3 mb-10">Common questions.</h2>
          <Accordion type="single" collapsible className="border-t border-border">
            {faqs.map((f, i) => (
              <AccordionItem key={i} value={`item-${i}`} className="border-b border-border">
                <AccordionTrigger data-testid={`faq-${i}`} className="font-display text-lg font-medium text-left hover:no-underline py-5">
                  {f.q}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground leading-relaxed pb-5">{f.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="bg-card">
        <div className="max-w-7xl mx-auto px-6 lg:px-10 py-12">
          <div className="grid md:grid-cols-4 gap-8">
            <div className="md:col-span-2">
              <div className="flex items-center gap-2">
                <div className="h-8 w-8 rounded-md bg-primary text-primary-foreground grid place-items-center font-display font-bold">B</div>
                <span className="font-display text-lg font-bold">Bharat Startup Desk</span>
              </div>
              <p className="text-sm text-muted-foreground mt-3 max-w-sm leading-relaxed">
                Your AI co-founder for the Indian founder journey. Educational guidance, not professional advice.
              </p>
              <div className="mt-5"><Disclaimer compact /></div>
            </div>
            <div>
              <div className="label-eyebrow text-muted-foreground">Product</div>
              <ul className="mt-4 space-y-2 text-sm">
                <li><Link to="/explore" className="hover:text-primary">Explore Idea</Link></li>
                <li><Link to="/onboarding" className="hover:text-primary">Onboarding</Link></li>
                <li><Link to="/dashboard" className="hover:text-primary">Dashboard</Link></li>
                <li><Link to="/admin" className="hover:text-primary">Admin</Link></li>
              </ul>
            </div>
            <div>
              <div className="label-eyebrow text-muted-foreground">Resources</div>
              <ul className="mt-4 space-y-2 text-sm">
                <li><a href="#features" className="hover:text-primary">Features</a></li>
                <li><a href="#how" className="hover:text-primary">How it works</a></li>
                <li><a href="#faq" className="hover:text-primary">FAQ</a></li>
                <li><a href="#pricing" className="hover:text-primary">Pricing</a></li>
              </ul>
            </div>
          </div>
          <div className="mt-10 pt-6 border-t border-border text-xs text-muted-foreground flex flex-col md:flex-row justify-between gap-3">
            <span>© {new Date().getFullYear()} Bharat Startup Desk. Made for India 🇮🇳</span>
            <span className="font-mono">v0.1 · MVP Preview</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
